
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef SLAVE_H
#define SLAVE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Slave_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Slave_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data Slave_Data;
extern REAL32 Temperture[1];		/* Mapped at index 0x2000, subindex 0x01 - 0x01 */
extern UNS8 ctr_para[1];		/* Mapped at index 0x2001, subindex 0x01 - 0x01 */
extern UNS8 sdo_test[1];		/* Mapped at index 0x2002, subindex 0x01 - 0x01 */

#endif // SLAVE_H
