
/* File generated by gen_cfile.py. Should not be modified. */

#include "Master.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 mstr_ctrl_data[] =		/* Mapped at index 0x2000, subindex 0x01 - 0x14 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
REAL32 slave_data[] =		/* Mapped at index 0x2001, subindex 0x01 - 0x14 */
  {
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000,
    0.000000
  };

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 Master_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 Master_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 Master_iam_a_slave = 0;

TIMER_HANDLE Master_heartBeatTimers[3] = {TIMER_NONE,TIMER_NONE,TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 Master_obj1000 = 0x0;	/* 0 */
                    subindex Master_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 Master_obj1001 = 0x0;	/* 0 */
                    subindex Master_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 Master_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex Master_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 Master_obj1005 = 0x40000080;	/* 0 */
                    subindex Master_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1005, NULL }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 Master_obj1006 = 0x3E8;	/* 1000 */
                    subindex Master_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1006, NULL }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 Master_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 Master_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 Master_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 Master_highestSubIndex_obj1016 = 4; /* number of subindex - 1*/
                    UNS32 Master_obj1016[] = 
                    {
                      0x103E8,	/* 1 */
                      0x203E8,	/* 2 */
                      0x303E8,	/* 3 */
											0x403E8,	/* 4 */
                      0x503E8,	/* 5 */
											0x603E8,	/* 6 */
                      0x703E8,	/* 7 */
											0x803E8,	/* 8 */
                      0x903E8,	/* 9 */
											0xa03E8,	/* 10 */
                      0xb03E8,	/* 11 */
											0xc03E8,	/* 12 */
                      0xd03E8,	/* 13 */
											0xe03E8,	/* 14 */
                      0xf03E8,	/* 15 */
											0x1003E8,	/* 16 */
											0x1103E8,	/* 17 */
											0x1203E8,	/* 18 */
                      0x1303E8,	/* 19 */
											0x1403E8	/* 20 */
                    };
                    subindex Master_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1016, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1016[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1016[1], NULL },
											 { RW, uint32, sizeof (UNS32), (void*)&Master_obj1016[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1016[3], NULL }
                     };

/* index 0x1017 :   Producer Heartbeat Time */ 
                    UNS16 Master_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
                    UNS8 Master_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 Master_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 Master_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 Master_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 Master_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex Master_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&Master_obj1018_Serial_Number, NULL }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 Master_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x601;	/* 1537 */
                    UNS32 Master_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x581;	/* 1409 */
                    UNS8 Master_obj1280_Node_ID_of_the_SDO_Server = 0x1;	/* 1 */
                    subindex Master_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1280, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1280_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1280_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1280_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1281 :   Client SDO 2 Parameter. */
                    UNS8 Master_highestSubIndex_obj1281 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1281_COB_ID_Client_to_Server_Transmit_SDO = 0x602;	/* 1538 */
                    UNS32 Master_obj1281_COB_ID_Server_to_Client_Receive_SDO = 0x582;	/* 1410 */
                    UNS8 Master_obj1281_Node_ID_of_the_SDO_Server = 0x2;	/* 2 */
                    subindex Master_Index1281[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1281, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1281_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1281_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1281_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1282 :   Client SDO 3 Parameter. */
                    UNS8 Master_highestSubIndex_obj1282 = 3; /* number of subindex - 1*/
                    UNS32 Master_obj1282_COB_ID_Client_to_Server_Transmit_SDO = 0x603;	/* 1539 */
                    UNS32 Master_obj1282_COB_ID_Server_to_Client_Receive_SDO = 0x583;	/* 1411 */
                    UNS8 Master_obj1282_Node_ID_of_the_SDO_Server = 0x3;	/* 3 */
                    subindex Master_Index1282[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1282, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1282_COB_ID_Client_to_Server_Transmit_SDO, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1282_COB_ID_Server_to_Client_Receive_SDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1282_Node_ID_of_the_SDO_Server, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 Master_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1400_COB_ID_used_by_PDO = 0x281;	/* 641 */
                    UNS8 Master_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1400_SYNC_start_value, NULL }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 Master_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1401_COB_ID_used_by_PDO = 0x282;	/* 642 */
                    UNS8 Master_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1401, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1401_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1401_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1401_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1401_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1401_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1401_SYNC_start_value, NULL }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 Master_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1402_COB_ID_used_by_PDO = 0x283;	/* 643 */
                    UNS8 Master_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1402, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1402_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1402_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1402_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1402_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1402_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1402_SYNC_start_value, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 Master_highestSubIndex_obj1600 = 1; /* number of subindex - 1*/
                    UNS32 Master_obj1600[] = 
                    {
                      0x20010120	/* 536936736 */
                    };
                    subindex Master_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1600, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1600[0], NULL }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 Master_highestSubIndex_obj1601 = 1; /* number of subindex - 1*/
                    UNS32 Master_obj1601[] = 
                    {
                      0x20010220	/* 536936992 */
                    };
                    subindex Master_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1601, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1601[0], NULL }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 Master_highestSubIndex_obj1602 = 1; /* number of subindex - 1*/
                    UNS32 Master_obj1602[] = 
                    {
                      0x20010320	/* 536937248 */
                    };
                    subindex Master_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1602, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1602[0], NULL }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 Master_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1800_COB_ID_used_by_PDO = 0x181;	/* 385 */
                    UNS8 Master_obj1800_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1800_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1800_SYNC_start_value, NULL }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 Master_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1801_COB_ID_used_by_PDO = 0x182;	/* 386 */
                    UNS8 Master_obj1801_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1801, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1801_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1801_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1801_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1801_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1801_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1801_SYNC_start_value, NULL }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 Master_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1802_COB_ID_used_by_PDO = 0x183;	/* 387 */
                    UNS8 Master_obj1802_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1802, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1802_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1802_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1802_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1802_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1802_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1802_SYNC_start_value, NULL }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 Master_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1803_COB_ID_used_by_PDO = 0x184;	/* 388 */
                    UNS8 Master_obj1803_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1803, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1803_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1803_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1803_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1803_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1803_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1803_SYNC_start_value, NULL }
                     };

/* index 0x1804 :   Transmit PDO 5 Parameter. */
                    UNS8 Master_highestSubIndex_obj1804 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1804_COB_ID_used_by_PDO = 0x185;	/* 389 */
                    UNS8 Master_obj1804_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1804_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1804_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1804_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1804_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1804[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1804, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1804_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1804_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1804_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1804_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1804_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1804_SYNC_start_value, NULL }
                     };

/* index 0x1805 :   Transmit PDO 6 Parameter. */
                    UNS8 Master_highestSubIndex_obj1805 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1805_COB_ID_used_by_PDO = 0x186;	/* 390 */
                    UNS8 Master_obj1805_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1805_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1805_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1805_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1805_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1805[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1805, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1805_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1805_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1805_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1805_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1805_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1805_SYNC_start_value, NULL }
                     };

/* index 0x1806 :   Transmit PDO 7 Parameter. */
                    UNS8 Master_highestSubIndex_obj1806 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1806_COB_ID_used_by_PDO = 0x187;	/* 391 */
                    UNS8 Master_obj1806_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1806_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1806_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1806_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1806_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1806[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1806, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1806_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1806_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1806_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1806_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1806_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1806_SYNC_start_value, NULL }
                     };

/* index 0x1807 :   Transmit PDO 8 Parameter. */
                    UNS8 Master_highestSubIndex_obj1807 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1807_COB_ID_used_by_PDO = 0x188;	/* 392 */
                    UNS8 Master_obj1807_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1807_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1807_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1807_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1807_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1807[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1807, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1807_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1807_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1807_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1807_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1807_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1807_SYNC_start_value, NULL }
                     };

/* index 0x1808 :   Transmit PDO 9 Parameter. */
                    UNS8 Master_highestSubIndex_obj1808 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1808_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 Master_obj1808_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1808_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1808_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1808_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1808_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1808[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1808, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1808_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1808_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1808_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1808_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1808_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1808_SYNC_start_value, NULL }
                     };

/* index 0x1809 :   Transmit PDO 10 Parameter. */
                    UNS8 Master_highestSubIndex_obj1809 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1809_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 Master_obj1809_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1809_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1809_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1809_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1809_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1809[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1809, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1809_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1809_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1809_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1809_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1809_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1809_SYNC_start_value, NULL }
                     };

/* index 0x180A :   Transmit PDO 11 Parameter. */
                    UNS8 Master_highestSubIndex_obj180A = 6; /* number of subindex - 1*/
                    UNS32 Master_obj180A_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 Master_obj180A_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj180A_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj180A_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj180A_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj180A_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index180A[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj180A, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj180A_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180A_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj180A_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180A_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj180A_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180A_SYNC_start_value, NULL }
                     };

/* index 0x180B :   Transmit PDO 12 Parameter. */
                    UNS8 Master_highestSubIndex_obj180B = 6; /* number of subindex - 1*/
                    UNS32 Master_obj180B_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 Master_obj180B_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj180B_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj180B_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj180B_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj180B_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index180B[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj180B, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj180B_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180B_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj180B_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180B_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj180B_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180B_SYNC_start_value, NULL }
                     };

/* index 0x180C :   Transmit PDO 13 Parameter. */
                    UNS8 Master_highestSubIndex_obj180C = 6; /* number of subindex - 1*/
                    UNS32 Master_obj180C_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 Master_obj180C_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj180C_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj180C_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj180C_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj180C_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index180C[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj180C, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj180C_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180C_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj180C_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180C_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj180C_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180C_SYNC_start_value, NULL }
                     };

/* index 0x180D :   Transmit PDO 14 Parameter. */
                    UNS8 Master_highestSubIndex_obj180D = 6; /* number of subindex - 1*/
                    UNS32 Master_obj180D_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 Master_obj180D_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj180D_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj180D_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj180D_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj180D_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index180D[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj180D, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj180D_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180D_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj180D_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180D_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj180D_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180D_SYNC_start_value, NULL }
                     };

/* index 0x180E :   Transmit PDO 15 Parameter. */
                    UNS8 Master_highestSubIndex_obj180E = 6; /* number of subindex - 1*/
                    UNS32 Master_obj180E_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 Master_obj180E_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj180E_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj180E_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj180E_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj180E_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index180E[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj180E, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj180E_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180E_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj180E_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180E_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj180E_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180E_SYNC_start_value, NULL }
                     };

/* index 0x180F :   Transmit PDO 16 Parameter. */
                    UNS8 Master_highestSubIndex_obj180F = 6; /* number of subindex - 1*/
                    UNS32 Master_obj180F_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 Master_obj180F_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj180F_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj180F_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj180F_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj180F_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index180F[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj180F, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj180F_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180F_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj180F_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180F_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj180F_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj180F_SYNC_start_value, NULL }
                     };

/* index 0x1810 :   Transmit PDO 17 Parameter. */
                    UNS8 Master_highestSubIndex_obj1810 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1810_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 Master_obj1810_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1810_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1810_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1810_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1810_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1810[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1810, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1810_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1810_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1810_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1810_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1810_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1810_SYNC_start_value, NULL }
                     };

/* index 0x1811 :   Transmit PDO 18 Parameter. */
                    UNS8 Master_highestSubIndex_obj1811 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1811_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 Master_obj1811_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1811_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1811_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1811_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1811_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1811[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1811, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1811_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1811_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1811_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1811_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1811_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1811_SYNC_start_value, NULL }
                     };

/* index 0x1812 :   Transmit PDO 19 Parameter. */
                    UNS8 Master_highestSubIndex_obj1812 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1812_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 Master_obj1812_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1812_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1812_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1812_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1812_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1812[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1812, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1812_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1812_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1812_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1812_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1812_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1812_SYNC_start_value, NULL }
                     };

/* index 0x1813 :   Transmit PDO 20 Parameter. */
                    UNS8 Master_highestSubIndex_obj1813 = 6; /* number of subindex - 1*/
                    UNS32 Master_obj1813_COB_ID_used_by_PDO = 0x0;	/* 0 */
                    UNS8 Master_obj1813_Transmission_Type = 0x0;	/* 0 */
                    UNS16 Master_obj1813_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 Master_obj1813_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 Master_obj1813_Event_Timer = 0x0;	/* 0 */
                    UNS8 Master_obj1813_SYNC_start_value = 0x0;	/* 0 */
                    subindex Master_Index1813[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1813, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1813_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1813_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1813_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1813_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&Master_obj1813_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Master_obj1813_SYNC_start_value, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A00 = 1; /* number of subindex - 1*/
                    UNS32 Master_obj1A00[] = 
                    {
                      0x20000108	/* 536871176 */
                    };
                    subindex Master_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A00[0], NULL }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A01 = 1; /* number of subindex - 1*/
                    UNS32 Master_obj1A01[] = 
                    {
                      0x20000208	/* 536871432 */
                    };
                    subindex Master_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A01, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A01[0], NULL }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A02 = 1; /* number of subindex - 1*/
                    UNS32 Master_obj1A02[] = 
                    {
                      0x20000308	/* 536871688 */
                    };
                    subindex Master_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A02, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&Master_obj1A02[0], NULL }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A03 = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1A03[] = 
                    {
                    };
                    subindex Master_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A03, NULL }
                     };

/* index 0x1A04 :   Transmit PDO 5 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A04 = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1A04[] = 
                    {
                    };
                    subindex Master_Index1A04[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A04, NULL }
                     };

/* index 0x1A05 :   Transmit PDO 6 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A05 = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1A05[] = 
                    {
                    };
                    subindex Master_Index1A05[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A05, NULL }
                     };

/* index 0x1A06 :   Transmit PDO 7 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A06 = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1A06[] = 
                    {
                    };
                    subindex Master_Index1A06[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A06, NULL }
                     };

/* index 0x1A07 :   Transmit PDO 8 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A07 = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1A07[] = 
                    {
                    };
                    subindex Master_Index1A07[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A07, NULL }
                     };

/* index 0x1A08 :   Transmit PDO 9 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A08 = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1A08[] = 
                    {
                    };
                    subindex Master_Index1A08[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A08, NULL }
                     };

/* index 0x1A09 :   Transmit PDO 10 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A09 = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1A09[] = 
                    {
                    };
                    subindex Master_Index1A09[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A09, NULL }
                     };

/* index 0x1A0A :   Transmit PDO 11 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A0A = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1A0A[] = 
                    {
                    };
                    subindex Master_Index1A0A[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A0A, NULL }
                     };

/* index 0x1A0B :   Transmit PDO 12 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A0B = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1A0B[] = 
                    {
                    };
                    subindex Master_Index1A0B[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A0B, NULL }
                     };

/* index 0x1A0C :   Transmit PDO 13 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A0C = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1A0C[] = 
                    {
                    };
                    subindex Master_Index1A0C[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A0C, NULL }
                     };

/* index 0x1A0D :   Transmit PDO 14 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A0D = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1A0D[] = 
                    {
                    };
                    subindex Master_Index1A0D[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A0D, NULL }
                     };

/* index 0x1A0E :   Transmit PDO 15 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A0E = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1A0E[] = 
                    {
                    };
                    subindex Master_Index1A0E[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A0E, NULL }
                     };

/* index 0x1A0F :   Transmit PDO 16 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A0F = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1A0F[] = 
                    {
                    };
                    subindex Master_Index1A0F[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A0F, NULL }
                     };

/* index 0x1A10 :   Transmit PDO 17 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A10 = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1A10[] = 
                    {
                    };
                    subindex Master_Index1A10[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A10, NULL }
                     };

/* index 0x1A11 :   Transmit PDO 18 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A11 = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1A11[] = 
                    {
                    };
                    subindex Master_Index1A11[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A11, NULL }
                     };

/* index 0x1A12 :   Transmit PDO 19 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A12 = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1A12[] = 
                    {
                    };
                    subindex Master_Index1A12[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A12, NULL }
                     };

/* index 0x1A13 :   Transmit PDO 20 Mapping. */
                    UNS8 Master_highestSubIndex_obj1A13 = 0; /* number of subindex - 1*/
                    UNS32 Master_obj1A13[] = 
                    {
                    };
                    subindex Master_Index1A13[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj1A13, NULL }
                     };

/* index 0x2000 :   Mapped variable mstr_ctrl_data */
                    UNS8 Master_highestSubIndex_obj2000 = 20; /* number of subindex - 1*/
                    subindex Master_Index2000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj2000, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&mstr_ctrl_data[0], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&mstr_ctrl_data[1], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&mstr_ctrl_data[2], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&mstr_ctrl_data[3], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&mstr_ctrl_data[4], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&mstr_ctrl_data[5], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&mstr_ctrl_data[6], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&mstr_ctrl_data[7], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&mstr_ctrl_data[8], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&mstr_ctrl_data[9], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&mstr_ctrl_data[10], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&mstr_ctrl_data[11], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&mstr_ctrl_data[12], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&mstr_ctrl_data[13], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&mstr_ctrl_data[14], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&mstr_ctrl_data[15], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&mstr_ctrl_data[16], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&mstr_ctrl_data[17], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&mstr_ctrl_data[18], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&mstr_ctrl_data[19], NULL }
                     };

/* index 0x2001 :   Mapped variable slave_data */
                    UNS8 Master_highestSubIndex_obj2001 = 20; /* number of subindex - 1*/
                    subindex Master_Index2001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&Master_highestSubIndex_obj2001, NULL },
                       { RW, real32, sizeof (REAL32), (void*)&slave_data[0], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&slave_data[1], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&slave_data[2], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&slave_data[3], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&slave_data[4], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&slave_data[5], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&slave_data[6], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&slave_data[7], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&slave_data[8], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&slave_data[9], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&slave_data[10], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&slave_data[11], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&slave_data[12], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&slave_data[13], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&slave_data[14], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&slave_data[15], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&slave_data[16], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&slave_data[17], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&slave_data[18], NULL },
                       { RW, real32, sizeof (REAL32), (void*)&slave_data[19], NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable Master_objdict[] = 
{
  { (subindex*)Master_Index1000,sizeof(Master_Index1000)/sizeof(Master_Index1000[0]), 0x1000},
  { (subindex*)Master_Index1001,sizeof(Master_Index1001)/sizeof(Master_Index1001[0]), 0x1001},
  { (subindex*)Master_Index1005,sizeof(Master_Index1005)/sizeof(Master_Index1005[0]), 0x1005},
  { (subindex*)Master_Index1006,sizeof(Master_Index1006)/sizeof(Master_Index1006[0]), 0x1006},
  { (subindex*)Master_Index1016,sizeof(Master_Index1016)/sizeof(Master_Index1016[0]), 0x1016},
  { (subindex*)Master_Index1018,sizeof(Master_Index1018)/sizeof(Master_Index1018[0]), 0x1018},
  { (subindex*)Master_Index1280,sizeof(Master_Index1280)/sizeof(Master_Index1280[0]), 0x1280},
  { (subindex*)Master_Index1281,sizeof(Master_Index1281)/sizeof(Master_Index1281[0]), 0x1281},
  { (subindex*)Master_Index1282,sizeof(Master_Index1282)/sizeof(Master_Index1282[0]), 0x1282},
  { (subindex*)Master_Index1400,sizeof(Master_Index1400)/sizeof(Master_Index1400[0]), 0x1400},
  { (subindex*)Master_Index1401,sizeof(Master_Index1401)/sizeof(Master_Index1401[0]), 0x1401},
  { (subindex*)Master_Index1402,sizeof(Master_Index1402)/sizeof(Master_Index1402[0]), 0x1402},
  { (subindex*)Master_Index1600,sizeof(Master_Index1600)/sizeof(Master_Index1600[0]), 0x1600},
  { (subindex*)Master_Index1601,sizeof(Master_Index1601)/sizeof(Master_Index1601[0]), 0x1601},
  { (subindex*)Master_Index1602,sizeof(Master_Index1602)/sizeof(Master_Index1602[0]), 0x1602},
  { (subindex*)Master_Index1800,sizeof(Master_Index1800)/sizeof(Master_Index1800[0]), 0x1800},
  { (subindex*)Master_Index1801,sizeof(Master_Index1801)/sizeof(Master_Index1801[0]), 0x1801},
  { (subindex*)Master_Index1802,sizeof(Master_Index1802)/sizeof(Master_Index1802[0]), 0x1802},
  { (subindex*)Master_Index1803,sizeof(Master_Index1803)/sizeof(Master_Index1803[0]), 0x1803},
  { (subindex*)Master_Index1804,sizeof(Master_Index1804)/sizeof(Master_Index1804[0]), 0x1804},
  { (subindex*)Master_Index1805,sizeof(Master_Index1805)/sizeof(Master_Index1805[0]), 0x1805},
  { (subindex*)Master_Index1806,sizeof(Master_Index1806)/sizeof(Master_Index1806[0]), 0x1806},
  { (subindex*)Master_Index1807,sizeof(Master_Index1807)/sizeof(Master_Index1807[0]), 0x1807},
  { (subindex*)Master_Index1808,sizeof(Master_Index1808)/sizeof(Master_Index1808[0]), 0x1808},
  { (subindex*)Master_Index1809,sizeof(Master_Index1809)/sizeof(Master_Index1809[0]), 0x1809},
  { (subindex*)Master_Index180A,sizeof(Master_Index180A)/sizeof(Master_Index180A[0]), 0x180A},
  { (subindex*)Master_Index180B,sizeof(Master_Index180B)/sizeof(Master_Index180B[0]), 0x180B},
  { (subindex*)Master_Index180C,sizeof(Master_Index180C)/sizeof(Master_Index180C[0]), 0x180C},
  { (subindex*)Master_Index180D,sizeof(Master_Index180D)/sizeof(Master_Index180D[0]), 0x180D},
  { (subindex*)Master_Index180E,sizeof(Master_Index180E)/sizeof(Master_Index180E[0]), 0x180E},
  { (subindex*)Master_Index180F,sizeof(Master_Index180F)/sizeof(Master_Index180F[0]), 0x180F},
  { (subindex*)Master_Index1810,sizeof(Master_Index1810)/sizeof(Master_Index1810[0]), 0x1810},
  { (subindex*)Master_Index1811,sizeof(Master_Index1811)/sizeof(Master_Index1811[0]), 0x1811},
  { (subindex*)Master_Index1812,sizeof(Master_Index1812)/sizeof(Master_Index1812[0]), 0x1812},
  { (subindex*)Master_Index1813,sizeof(Master_Index1813)/sizeof(Master_Index1813[0]), 0x1813},
  { (subindex*)Master_Index1A00,sizeof(Master_Index1A00)/sizeof(Master_Index1A00[0]), 0x1A00},
  { (subindex*)Master_Index1A01,sizeof(Master_Index1A01)/sizeof(Master_Index1A01[0]), 0x1A01},
  { (subindex*)Master_Index1A02,sizeof(Master_Index1A02)/sizeof(Master_Index1A02[0]), 0x1A02},
  { (subindex*)Master_Index1A03,sizeof(Master_Index1A03)/sizeof(Master_Index1A03[0]), 0x1A03},
  { (subindex*)Master_Index1A04,sizeof(Master_Index1A04)/sizeof(Master_Index1A04[0]), 0x1A04},
  { (subindex*)Master_Index1A05,sizeof(Master_Index1A05)/sizeof(Master_Index1A05[0]), 0x1A05},
  { (subindex*)Master_Index1A06,sizeof(Master_Index1A06)/sizeof(Master_Index1A06[0]), 0x1A06},
  { (subindex*)Master_Index1A07,sizeof(Master_Index1A07)/sizeof(Master_Index1A07[0]), 0x1A07},
  { (subindex*)Master_Index1A08,sizeof(Master_Index1A08)/sizeof(Master_Index1A08[0]), 0x1A08},
  { (subindex*)Master_Index1A09,sizeof(Master_Index1A09)/sizeof(Master_Index1A09[0]), 0x1A09},
  { (subindex*)Master_Index1A0A,sizeof(Master_Index1A0A)/sizeof(Master_Index1A0A[0]), 0x1A0A},
  { (subindex*)Master_Index1A0B,sizeof(Master_Index1A0B)/sizeof(Master_Index1A0B[0]), 0x1A0B},
  { (subindex*)Master_Index1A0C,sizeof(Master_Index1A0C)/sizeof(Master_Index1A0C[0]), 0x1A0C},
  { (subindex*)Master_Index1A0D,sizeof(Master_Index1A0D)/sizeof(Master_Index1A0D[0]), 0x1A0D},
  { (subindex*)Master_Index1A0E,sizeof(Master_Index1A0E)/sizeof(Master_Index1A0E[0]), 0x1A0E},
  { (subindex*)Master_Index1A0F,sizeof(Master_Index1A0F)/sizeof(Master_Index1A0F[0]), 0x1A0F},
  { (subindex*)Master_Index1A10,sizeof(Master_Index1A10)/sizeof(Master_Index1A10[0]), 0x1A10},
  { (subindex*)Master_Index1A11,sizeof(Master_Index1A11)/sizeof(Master_Index1A11[0]), 0x1A11},
  { (subindex*)Master_Index1A12,sizeof(Master_Index1A12)/sizeof(Master_Index1A12[0]), 0x1A12},
  { (subindex*)Master_Index1A13,sizeof(Master_Index1A13)/sizeof(Master_Index1A13[0]), 0x1A13},
  { (subindex*)Master_Index2000,sizeof(Master_Index2000)/sizeof(Master_Index2000[0]), 0x2000},
  { (subindex*)Master_Index2001,sizeof(Master_Index2001)/sizeof(Master_Index2001[0]), 0x2001},
};

const indextable * Master_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	(void)d;
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1005: i = 2;break;
		case 0x1006: i = 3;break;
		case 0x1016: i = 4;break;
		case 0x1018: i = 5;break;
		case 0x1280: i = 6;break;
		case 0x1281: i = 7;break;
		case 0x1282: i = 8;break;
		case 0x1400: i = 9;break;
		case 0x1401: i = 10;break;
		case 0x1402: i = 11;break;
		case 0x1600: i = 12;break;
		case 0x1601: i = 13;break;
		case 0x1602: i = 14;break;
		case 0x1800: i = 15;break;
		case 0x1801: i = 16;break;
		case 0x1802: i = 17;break;
		case 0x1803: i = 18;break;
		case 0x1804: i = 19;break;
		case 0x1805: i = 20;break;
		case 0x1806: i = 21;break;
		case 0x1807: i = 22;break;
		case 0x1808: i = 23;break;
		case 0x1809: i = 24;break;
		case 0x180A: i = 25;break;
		case 0x180B: i = 26;break;
		case 0x180C: i = 27;break;
		case 0x180D: i = 28;break;
		case 0x180E: i = 29;break;
		case 0x180F: i = 30;break;
		case 0x1810: i = 31;break;
		case 0x1811: i = 32;break;
		case 0x1812: i = 33;break;
		case 0x1813: i = 34;break;
		case 0x1A00: i = 35;break;
		case 0x1A01: i = 36;break;
		case 0x1A02: i = 37;break;
		case 0x1A03: i = 38;break;
		case 0x1A04: i = 39;break;
		case 0x1A05: i = 40;break;
		case 0x1A06: i = 41;break;
		case 0x1A07: i = 42;break;
		case 0x1A08: i = 43;break;
		case 0x1A09: i = 44;break;
		case 0x1A0A: i = 45;break;
		case 0x1A0B: i = 46;break;
		case 0x1A0C: i = 47;break;
		case 0x1A0D: i = 48;break;
		case 0x1A0E: i = 49;break;
		case 0x1A0F: i = 50;break;
		case 0x1A10: i = 51;break;
		case 0x1A11: i = 52;break;
		case 0x1A12: i = 53;break;
		case 0x1A13: i = 54;break;
		case 0x2000: i = 55;break;
		case 0x2001: i = 56;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &Master_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status Master_PDO_status[20] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index Master_firstIndex = {
  0, /* SDO_SVR */
  6, /* SDO_CLT */
  9, /* PDO_RCV */
  12, /* PDO_RCV_MAP */
  15, /* PDO_TRS */
  35 /* PDO_TRS_MAP */
};

const quick_index Master_lastIndex = {
  0, /* SDO_SVR */
  8, /* SDO_CLT */
  11, /* PDO_RCV */
  14, /* PDO_RCV_MAP */
  34, /* PDO_TRS */
  54 /* PDO_TRS_MAP */
};

const UNS16 Master_ObjdictSize = sizeof(Master_objdict)/sizeof(Master_objdict[0]); 

CO_Data Master_Data = CANOPEN_NODE_DATA_INITIALIZER(Master);

