
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MASTER_H
#define MASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Master_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data Master_Data;
extern UNS8 mstr_ctrl_data[20];		/* Mapped at index 0x2000, subindex 0x01 - 0x14 */
extern REAL32 slave_data[20];		/* Mapped at index 0x2001, subindex 0x01 - 0x14 */

#endif // MASTER_H
